/*
 * Copyright (C) 2003 Bart Trojanowski <bart@jukie.net>
 *
 * This file is a part of the elfsign utility
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#ident "@(#)ep_session.h 1.1      03/05/25 Bart Trojanowski <bart@jukie.net>"

#ifndef _EP_SESSION_H
#define _EP_SESSION_H

typedef struct elfgpg_session_s {
	/* what file are we currently working on */
	const char 	*file;
	int 		fd;

	/* elf processing variables */
	Elf 		*elf;
	Elf32_Ehdr 	*ehdr;
	Elf32_Phdr 	*phdr;

	/* the two sections generated by elfgpg */
	Elf32_Shdr 	*pgpsig_hdr;
	Elf_Scn 	*pgpsig_scn;
	Elf_Data 	*pgpsig_data;

	Elf32_Shdr 	*pgptab_hdr;
	Elf_Scn 	*pgptab_scn;
	Elf_Data 	*pgptab_data;
} elfgpg_session_t;


#endif /* _EP_SESSION_H */
